import assert from "node:assert/strict";
import { mkdirSync } from "node:fs";
import path from "node:path";
import { chromium } from "playwright-core";
import { fixtureSkill, skillAuthoringFixture } from "../src/server/testing/skill-authoring-fixture.js";

const output = "/tmp/openbot-skill-authoring-qa";
mkdirSync(output, { recursive: true });
const fixture = await skillAuthoringFixture();
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
try {
  const proposal = await fixture.propose();
  browser = await chromium.launch({ executablePath: process.env.OPENBOT_CHROME_PATH || "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.setDefaultTimeout(12_000);
  await page.goto(fixture.base + "/studio.html?thread=bot-nova");
  const controls = page.locator(".run-controls").filter({ hasText: "Save skill: Invoice reconciliation" });
  const approve = controls.getByRole("button", { name: "Approve action", exact: true });
  await approve.waitFor();
  assert.equal(await approve.isDisabled(), true);
  await controls.getByText("Review the full action", { exact: true }).click();
  assert.equal(await controls.getByText(fixtureSkill.instructions, { exact: true }).count(), 1);
  await page.waitForFunction(() => [...document.querySelectorAll<HTMLButtonElement>(".run-controls button")].some(button => button.textContent === "Approve action" && !button.disabled));
  assert.equal(await approve.isEnabled(), true);
  await controls.scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(output, "review-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await controls.scrollIntoViewIfNeeded();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), "Phone review does not overflow horizontally");
  await page.screenshot({ path: path.join(output, "review-phone.png") });
  await approve.click();
  await fixture.until(() => fixture.db.getApprovedAction(proposal.approvalId)?.status === "completed");
  assert.equal(fixture.db.listWorkflows().length, 1);
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto(fixture.base + "/studio.html?thread=bot-nova&panel=teach");
  await page.getByText("Your learned workflows", { exact: true }).click();
  const skillRow = page.locator(".workflow-list > div").filter({ hasText: "/invoice-reconciliation" });
  await skillRow.waitFor();
  assert.ok((await skillRow.innerText()).includes("No starting website needed"));
  await skillRow.getByRole("button", { name: "Edit", exact: true }).click();
  const urlField = page.getByLabel("Starting web page (optional)", { exact: true });
  assert.equal(await urlField.inputValue(), "");
  assert.equal(await urlField.getAttribute("required"), null);
  await page.screenshot({ path: path.join(output, "edit-general-skill.png") });
  assert.deepEqual(errors, []);
  console.log(`PASS: desktop + 390px review, approval gating, exact host-saved instructions, learned skill list and optional website editor. Screenshots: ${output}. Deterministic runtime; no accounts or live model used.`);
} finally { await browser?.close(); await fixture.close(); }
