// Synthetic content in the production database/API; real Electron renderer.
// No model credentials, live accounts or dispatch. Run after npm run build.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import { spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createServer } from 'node:net';
import { setTimeout as delay } from 'node:timers/promises';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { _electron, chromium } from 'playwright-core';
import { OpenBotDatabase } from '../src/server/database.js';
const root = mkdtempSync(path.join(tmpdir(), 'openbot-figma-'));
const data = path.join(root, 'data');
const output = path.resolve('qa/figma-implementation/actual');
mkdirSync(output, {recursive:true});
const db = new OpenBotDatabase(root, {dataDir:data});
const roster = [
 ['Pixel','blob','#d86889','Software & ideas','A little more you.'],
 ['Scout','sprout','#299575','Research & examples','Ready for your review.'],
 ['Nova','nova','#6757d9','Planning','A plan for the week.'],
 ['Sage','pebble','#8780bf','Perspective','A fresh perspective.'],
 ['Atlas','orbit','#687588','Details','The details are in good hands.'],
 ['Finch','sunny','#c28735','A little help','A little help, right on time.'],
] as const;
const bots = roster.map(([name,mascot,color,role]) => db.createBot({name,mascot:mascot as any,color,role,emoji:'',instructions:'Synthetic Figma QA. No external work.',computerEnabled:false,browserEnabled:false}));
const pixel=bots[0]!, scout=bots[1]!;
for (const bot of bots) db.updateBot(bot.id,{providerInstanceId:db.listProviders()[0]!.id,model:'fixture/no-dispatch'});
for(const bot of bots.slice(0,2)) db.updateThread(bot.threadId,{pinned:true});
for(let i=1;i<bots.length;i++) db.addMessage({threadId:bots[i]!.threadId,senderType:'bot',senderId:bots[i]!.id,body:roster[i]![4]});
const threadId=pixel.threadId;
db.addMessage({threadId,senderType:'user',senderId:null,body:'Give this launch note a little more us.  \nAsk Scout to check the examples.'});
db.addMessage({threadId,senderType:'bot',senderId:pixel.id,body:'On it. I’ll ask Scout to keep me honest.'});
const run=db.createRun({threadId,botId:pixel.id,prompt:'Prepare a launch note',status:'completed'});
const message=db.addMessage({threadId,senderType:'bot',senderId:pixel.id,runId:run.id,body:''});
const text='# A little more you.\n\nI’m building a little team. Not another inbox.\nA few good ideas, and someone to help carry them.\n\n## Usage snapshot\n\n| Category | Value | Reporting |\n| --- | ---: | --- |\n| Input tokens | 15348 | Reported |\n| Output tokens | 37 | Reported |\n\n- [x] Stored result\n- [ ] Owner review\n\n```text\nA code sample stays readable.\n```\n';
const filePath=path.join(data,'attachments','figma-launch-note','Meet OpenBot.md');
mkdirSync(path.dirname(filePath),{recursive:true});writeFileSync(filePath,text);
const file=db.createAttachment({threadId,messageId:message.id,name:'Meet OpenBot.md',mime:'text/markdown',size:Buffer.byteLength(text),storagePath:filePath,source:'artifact',artifactKey:'launch-note',revision:2,analysis:{detectedMime:'text/markdown',kind:'text',processingStatus:'ready',summary:null,extractedText:text,metadata:{classification:'deliverable'},previewable:false}});
const review=db.createRun({threadId,botId:scout.id,parentRunId:run.id,prompt:'Independent review for Pixel: check the exact stored launch note.',status:'completed'});
db.updateRun(review.id,{summary:'AGREE: The draft keeps the two examples in the supplied note.\nSynthetic review fixture, bound to revision 2. No live reviewer model ran.'});
db.saveExtensionRecord('run-review',review.id,{artifacts:[{id:file.id,name:file.name,revision:file.revision,sha256:createHash('sha256').update(text).digest('hex')}]});
db.addMessage({threadId,senderType:'user',senderId:null,body:'That’s the one. Another look every Monday at 9?'});
// Do not invent a scheduled outcome: this fixture has no live recurring work.
db.close();
const socket=createServer();await new Promise<void>(resolve=>socket.listen(0,'127.0.0.1',resolve));const port=(socket.address() as any).port;await new Promise<void>(resolve=>socket.close(()=>resolve()));
const base=`http://127.0.0.1:${port}`;
const bundle=process.env.OPENBOT_TEST_BUNDLE;
const serverRoot=bundle ? path.join(bundle,'app') : process.cwd();
const server=spawn(bundle ? path.join(bundle,'bin/node') : process.execPath,['--import','tsx','src/server/index.ts'],{cwd:serverRoot,stdio:['ignore','pipe','pipe'],env:{...process.env,PATH:bundle ? `${path.join(bundle,'bin')}${path.delimiter}${process.env.PATH || ''}` : process.env.PATH,OPENBOT_LOAD_ENV:'0',OPENBOT_DATA_DIR:data,OPENBOT_PORT:String(port),OPENBOT_HOST:'127.0.0.1',OPENBOT_APP_URL:base,NODE_ENV:'production',OPENBOT_DEPLOYMENT_MODE:'local'}});
let log='';server.stdout?.on('data',c=>log+=c);server.stderr?.on('data',c=>log+=c);
let electron:Awaited<ReturnType<typeof _electron.launch>>|undefined;
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try {
 let ready=false;for(let i=0;i<600;i++){try{if((await fetch(base+'/api/healthz')).ok){ready=true;break}}catch{}await delay(150)}assert.ok(ready,log);
 const mcp=new Client({name:'figma-conversation-qa',version:'1.0.0'});
 const transport=new StdioClientTransport({command:process.execPath,args:['--import','tsx','mcp/openbot.ts'],env:{...Object.fromEntries(Object.entries(process.env).filter((entry):entry is [string,string]=>typeof entry[1]==='string')),OPENBOT_URL:base,OPENBOT_DATA_DIR:data,OPENBOT_MCP_FULL:'0'},stderr:'pipe'});
 await mcp.connect(transport);
 try{const tools=await mcp.listTools();assert.ok(tools.tools.some(t=>t.name==='studio_state'));const result=await mcp.callTool({name:'studio_state',arguments:{threadId,messageLimit:20}});assert.ok(!result.isError);assert.ok(JSON.stringify(result.content).includes(pixel.id));console.log(`PASS isolated MCP: ${tools.tools.length} discovered tools; synthetic roster and conversation verified`);}finally{await mcp.close()}
 electron=await _electron.launch({executablePath:process.env.OPENBOT_TEST_EXECUTABLE || path.resolve('desktop/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'),args:process.env.OPENBOT_TEST_EXECUTABLE ? [] : [path.resolve('desktop/main.mjs')],env:{...process.env,OPENBOT_DEV_URL:`${base}/?thread=${threadId}`,OPENBOT_DESKTOP_USER_DATA:path.join(root,'electron'),OPENBOT_QA_WIDTH:'1440',OPENBOT_QA_HEIGHT:'940'}});
 const page=await electron.firstWindow();page.setDefaultTimeout(10000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.locator('#studio-message').waitFor();await page.getByRole('button',{name:'Pixel',exact:true}).click();await page.getByText('Give this launch note a little more us.',{exact:false}).waitFor();
 await page.evaluate(()=>document.fonts.ready);await page.emulateMedia({reducedMotion:'reduce',colorScheme:'light'});await delay(800);
 await page.mouse.move(1400,900);await page.locator('.chat-scroll').evaluate(el=>el.scrollTop=0);
 await page.screenshot({path:path.join(output,'electron-1440x940.png'),scale:'css'});
 console.log('CAPTURE',await page.evaluate(()=>({width:innerWidth,height:innerHeight,scale:devicePixelRatio})),root);
 if(process.env.OPENBOT_FIGMA_CAPTURE_ONLY==='1'){console.log('Capture only');}else{
 const novaRow=()=>page.getByRole('button',{name:'Nova',exact:true}).locator('..');
 await novaRow().hover();await page.getByRole('button',{name:'Conversation actions for Nova',exact:true}).click();await page.getByRole('button',{name:'Pin Nova to the top',exact:true}).click();
 await page.locator('.pinned-zone').getByRole('button',{name:'Nova',exact:true}).waitFor();
 await page.reload();await page.locator('.pinned-zone').getByRole('button',{name:'Nova',exact:true}).waitFor();
 const unpinResponse=page.waitForResponse(response=>response.url().endsWith('/api/threads/'+bots[2]!.threadId)&&response.request().method()==='PATCH');
 await page.getByRole('button',{name:'Unpin Nova',exact:true}).press('Enter');
 assert.equal((await unpinResponse).status(),200,'keyboard unpin reaches the host');
 await page.locator('.pinned-zone').getByRole('button',{name:'Nova',exact:true}).waitFor({state:'detached'});
 await novaRow().hover();await page.getByRole('button',{name:'Conversation actions for Nova',exact:true}).click();await page.getByRole('button',{name:'Archive Nova',exact:true}).click();
 await page.getByRole('button',{name:'Tap again to archive Nova',exact:true}).click();
 await page.locator('.archived-chats > summary').click();
 await page.getByRole('button',{name:'Unhide Nova',exact:true}).click();await page.getByRole('button',{name:'Archive Nova',exact:true}).waitFor();
 const failedPin='**/api/threads/'+bots[2]!.threadId;
 await page.route(failedPin,route=>route.request().method()==='PATCH' ? route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Synthetic save failure'})}) : route.continue());
 await novaRow().hover();await page.getByRole('button',{name:'Conversation actions for Nova',exact:true}).click();await page.getByRole('button',{name:'Pin Nova to the top',exact:true}).click();
 await page.getByRole('alert').filter({hasText:'Synthetic save failure'}).waitFor();
 assert.equal(await page.locator('.pinned-zone').getByRole('button',{name:'Nova',exact:true}).count(),0);
 await page.unroute(failedPin);await page.getByRole('button',{name:'Dismiss',exact:true}).click();
 console.log('PASS conversation actions: pointer pin, reload persistence, keyboard unpin, archive/restore through real host; injected failed save stays visible');
 const legacyFixture=new OpenBotDatabase(root,{dataDir:data});
 const legacy=legacyFixture.createGroupThread('Older launch chat',[pixel.id,scout.id]);
 legacyFixture.addMessage({threadId:legacy.id,senderType:'user',senderId:null,body:'Keep this conversation for the record.'});
 legacyFixture.close();
 await page.reload();
 await page.getByRole('button',{name:'Older launch chat',exact:true}).waitFor();
 assert.equal(await page.locator('.project-rooms').count(),0,'past multi-teammate chats use the regular Recent list');
 await page.getByRole('button',{name:'New conversation',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Start a shared chat'}).count(),0,'new conversations start with one teammate');
 await page.keyboard.press('Escape');
 await page.getByRole('dialog',{name:'New conversation'}).waitFor({state:'detached'});
 await page.getByRole('button',{name:'Older launch chat',exact:true}).click();
 await page.waitForFunction(id=>new URL(location.href).searchParams.get('thread')===id,legacy.id);
 await page.getByRole('button',{name:'About Older launch chat',exact:true}).waitFor();
 await page.getByRole('button',{name:'Conversation details',exact:true}).click();
 await page.getByRole('button',{name:'Manage participants',exact:true}).click();
 const legacyEditor=page.getByRole('dialog',{name:'Conversation participants'});
 await legacyEditor.getByRole('textbox',{name:'Chat name'}).fill('Launch archive');
 await legacyEditor.getByRole('button',{name:'Save conversation'}).click();
 await page.getByRole('button',{name:'Launch archive',exact:true}).waitFor();
 await page.goto(`${base}/?thread=${threadId}`);
 await page.getByRole('button',{name:'About Pixel',exact:true}).waitFor();
 console.log('PASS chat simplification: no new group flow; older multi-teammate chat stays available and editable');
 const archiveFixture=new OpenBotDatabase(root,{dataDir:data});
 for(let i=1;i<=7;i++){const room=archiveFixture.createGroupThread(`Archived project ${i}`, [pixel.id,scout.id]);archiveFixture.updateThread(room.id,{hidden:true});}archiveFixture.close();
 await page.reload();await page.locator('.archived-chats > summary').click();
 const archiveRows=await page.locator('.archived-cell').evaluateAll(rows=>rows.map(row=>row.getBoundingClientRect().height));
 assert.equal(archiveRows.length,7);assert.ok(archiveRows.every(height=>height<=64),'archived rows stay compact');
 await page.locator('.archived-chats').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'archived-chats.png'),scale:'css'});
 await page.locator('.archived-chats > summary').click();
 const input=page.locator('#studio-message');await input.fill('Pixel draft retained');await delay(700);
 await page.getByRole('button',{name:'Scout',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#studio-message')?.getAttribute('placeholder')==='What’s next, Scout?');await input.fill('Scout has a different draft');await delay(700);
 await page.getByRole('button',{name:'Pixel',exact:true}).click();await page.waitForFunction(()=> (document.querySelector('#studio-message') as HTMLTextAreaElement)?.value==='Pixel draft retained');
 await page.reload();await input.waitFor();await page.waitForFunction(()=> (document.querySelector('#studio-message') as HTMLTextAreaElement)?.value==='Pixel draft retained');
 await input.fill('');await delay(700);
 await page.getByLabel('Message options').click();assert.ok(await page.getByRole('button',{name:'Add files',exact:true}).isVisible());await page.getByLabel('Message options').click();
 const article=page.locator('.chat-message').first();await article.hover();await article.getByLabel('React to this message').click();await article.getByRole('button',{name:'React 👍',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.message-reaction-chip')?.textContent?.includes('👍'));
 const state=await page.evaluate(async id=>(await fetch('/api/state?threadId='+encodeURIComponent(id))).json(),threadId);assert.ok(state.messages.some((m:any)=>m.reactions?.some((r:any)=>r.emoji==='👍')),'reaction persisted through real API');
 await page.locator('.delivery-reviews > summary').click();assert.ok(await page.getByText('The draft keeps the two examples in the supplied note.',{exact:false}).first().isVisible());await page.locator('.delivery-reviews > summary').click();
 const downloadPath=path.join(root,'downloaded-launch-note.md');
 await electron.evaluate(({session},savePath)=>{session.defaultSession.once('will-download',(_event: unknown,item: {setSavePath(path: string): void; once(event: string, listener: (event: unknown, state: string) => void): void})=>{item.setSavePath(savePath);item.once('done',(_event: unknown,state: string)=>{(globalThis as any).__figmaDownload=state})})},downloadPath);
 await page.getByRole('link',{name:'Open Meet OpenBot.md, revision 2',exact:true}).click();
 await page.getByRole('complementary',{name:'Document preview'}).waitFor();
 assert.equal(await page.locator('.document-reader table tbody tr').count(),2,'GFM table renders structured rows');
 assert.equal(await page.locator('.document-reader input[type=checkbox]').count(),2,'GFM tasks render');
 await page.screenshot({path:path.join(output,'document-preview.png'),scale:'css'});
 await page.getByRole('link',{name:'Open original',exact:true}).click();
 let downloadState='';for(let i=0;i<60;i++){downloadState=await electron.evaluate(()=> (globalThis as any).__figmaDownload);if(downloadState)break;await delay(100)}assert.equal(downloadState,'completed','Electron saves actual delivered file');
 await page.getByRole('button',{name:'Ask for a change',exact:true}).click();
 await page.waitForFunction(()=> (document.querySelector('#studio-message') as HTMLTextAreaElement)?.value.includes('revision 2'));
 await input.fill('');await delay(700);
 await page.getByRole('button',{name:'Close document',exact:true}).click();

 const original=await page.evaluate(async url=>(await fetch(url)).text(),file.url);assert.equal(original,text,'document uses actual stored bytes');
 await page.getByLabel('Find a conversation').fill('Scout');assert.equal(await page.getByRole('button',{name:'Pixel',exact:true}).count(),0);await page.getByLabel('Find a conversation').fill('');
 await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.screenshot({path:path.join(output,'electron-dark.png'),scale:'css'});await page.emulateMedia({colorScheme:'light',reducedMotion:'reduce'});
 await page.getByRole('button',{name:'New conversation',exact:true}).click();
 await page.setViewportSize({width:1154,height:768});
 await page.screenshot({path:path.resolve('qa/sidebar-polish/new-conversation-1154x768.png'),scale:'css'});
 await page.setViewportSize({width:1440,height:940});
 await page.keyboard.press('Escape');
 assert.deepEqual(errors,[]);
 console.log('PASS Electron: 1440x940, real backend, draft switching/reload, options, reaction persistence, search, stored artifact bytes');
 }
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const phone=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
 phone.on('pageerror',error=>errors.push(`phone: ${error.message}`));
 await phone.goto(`${base}/?thread=${threadId}`);await phone.locator('#studio-message').waitFor();await phone.emulateMedia({reducedMotion:'reduce'});await delay(500);
 await phone.locator('.chat-scroll').evaluate(el=>el.scrollTop=0);await phone.screenshot({path:path.join(output,'phone-390x844.png')});
 assert.ok(await phone.getByText('Give this launch note a little more us.',{exact:false}).isVisible());
 assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'phone has no horizontal page overflow');
 await phone.setViewportSize({width:320,height:844});await phone.screenshot({path:path.join(output,'phone-320x844.png')});
 assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px has no horizontal overflow');
 const reviewBounds=await phone.locator('.delivery-reviews > summary').boundingBox();assert.ok(reviewBounds && reviewBounds.height<90,'review byline stays readable at 320px');
 console.log('PASS phone emulation: visible messages, 390px and 320px, no horizontal overflow');
 if (process.env.OPENBOT_TEST_ALL_SCREENS === '1') {
   await phone.setViewportSize({width:390,height:844});
   await phone.getByRole('link',{name:'Open Meet OpenBot.md, revision 2',exact:true}).click();
   await phone.getByRole('dialog',{name:'Document preview'}).waitFor();
   await phone.screenshot({path:path.join(output,'phone-document.png')});
   await phone.getByRole('button',{name:'Close document',exact:true}).click();
   await page.goto(`${base}/?thread=${threadId}`);
   const search = page.getByLabel('Find a conversation'); await search.waitFor(); await search.focus();
   const focus = await search.evaluate(input => ({ input: getComputedStyle(input).outlineStyle, wrapper: getComputedStyle(input.parentElement!).outlineStyle }));
   assert.equal(focus.input, 'none'); assert.equal(focus.wrapper, 'solid');
   await page.screenshot({path:path.join(output,'search-focus.png'),scale:'css'});
   const panels = ['team','provider','connectors','routines','projects','artifacts','teach','control','usage','remote','live','bot','files','computer'];
   for (const panel of panels) {
     await page.goto(`${base}/?thread=${threadId}&panel=${panel}`);
     await page.locator(`.capability-${panel}`).waitFor();
     if (panel === 'provider') await page.getByText('Checking your connections…',{exact:true}).waitFor({state:'hidden',timeout:90000});
     if (panel === 'connectors') {
       await page.getByText('Use the apps you already have',{exact:true}).waitFor();
       assert.equal(await page.locator('#direct-connection-settings[open]').count(),0,'a fresh studio does not lead with OAuth setup');
       assert.equal(await page.getByRole('button',{name:'Connect Gmail',exact:true}).isVisible(),false,'direct connectors start behind an optional disclosure');
     }
     await delay(600);
     assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), `${panel}: desktop overflow`);
     await page.mouse.move(1400,900);
     await page.screenshot({path:path.join(output,`workspace-${panel}.png`),scale:'css'});
     assert.ok(await page.locator('.capabilities').evaluate(el=>el.scrollWidth<=el.clientWidth+1), `${panel}: desktop content clipping`);
     const scrollable=page.locator('.settings-page-content');
     if(await scrollable.evaluate(el=>el.scrollHeight>el.clientHeight+40)){await scrollable.evaluate(el=>el.scrollTop=el.scrollHeight);await page.screenshot({path:path.join(output,`workspace-${panel}-bottom.png`),scale:'css'});}
     await phone.setViewportSize({width:390,height:844});
     await phone.goto(`${base}/?thread=${threadId}&panel=${panel}`);
     await phone.locator(`.capability-${panel}`).waitFor(); await delay(250);
     assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), `${panel}: phone overflow`);
     await phone.screenshot({path:path.join(output,`phone-${panel}.png`)});
     await phone.setViewportSize({width:320,height:844});
     assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), `${panel}: 320px phone overflow`);
     assert.ok(await phone.locator('.capabilities').evaluate(el=>el.scrollWidth<=el.clientWidth+1), `${panel}: 320px content clipping`);
   await phone.locator('.settings-mobile-back').click();
   assert.ok(await phone.locator('.settings-page-sidebar').isVisible(), `${panel}: phone returns to menu`);
   }
   await page.goto(`${base}/?thread=${threadId}&panel=provider`);
   await page.getByRole('button',{name:'Set up Ollama',exact:true}).click();
   assert.equal(await page.getByRole('combobox',{name:'Provider',exact:true}).inputValue(),'ollama');
   assert.equal(await page.getByRole('textbox',{name:'API address',exact:true}).inputValue(),'http://127.0.0.1:11434/v1');
   await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === 'Model IDs');
   await page.screenshot({path:path.join(output,'workspace-local-model-setup.png'),scale:'css'});
   await page.goto(`${base}/?thread=${threadId}&panel=connectors`);
   await page.getByRole('button',{name:"Review Pixel's browser access",exact:true}).click();
   await page.locator('.capability-bot').waitFor();
   await page.goto(`${base}/?thread=${threadId}&panel=connectors`);
   await page.locator('#direct-connection-settings').waitFor();
   if (await page.locator('.direct-connections[open]').count() === 0) await page.locator('.direct-connections > summary').click();
   await page.getByRole('button',{name:'Connect Gmail',exact:true}).click();
   await page.locator('#direct-connection-settings[open]').waitFor();
   await page.locator('#connector-settings-google[open]').waitFor();
   await delay(600);
   await page.screenshot({path:path.join(output,'workspace-connect-gmail.png'),scale:'css'});
   await phone.setViewportSize({width:390,height:844});
   await phone.goto(`${base}/?thread=${threadId}&panel=connectors`);
   if (await phone.locator('.direct-connections[open]').count() === 0) await phone.locator('.direct-connections > summary').click();
   await phone.getByRole('button',{name:'Connect Gmail',exact:true}).click();
   await phone.locator('#direct-connection-settings[open]').waitFor();
   await phone.locator('#connector-settings-google[open]').waitFor();
   await delay(600);
   await phone.screenshot({path:path.join(output,'phone-connect-gmail.png')});
   const browserAccessFixture=new OpenBotDatabase(root,{dataDir:data});
   browserAccessFixture.updateBot(pixel.id,{browserEnabled:true});browserAccessFixture.close();
   await page.goto(`${base}/?thread=${threadId}&panel=connectors`);
   await page.getByRole('button',{name:"Open Pixel's chat",exact:true}).click();
   await page.locator('#studio-message').waitFor();
   assert.equal(new URL(page.url()).searchParams.get('thread'),threadId);
   const browserAccessReset=new OpenBotDatabase(root,{dataDir:data});
   browserAccessReset.updateBot(pixel.id,{browserEnabled:false});browserAccessReset.close();
   await page.goto(`${base}/?thread=${threadId}&panel=connectors`);
   await page.emulateMedia({reducedMotion:'no-preference'});
   assert.equal(await page.locator('.capabilities').evaluate(el=>getComputedStyle(el).animationName),'workspace-arrive');
   await page.emulateMedia({reducedMotion:'reduce'});
   assert.equal(await page.locator('.capabilities').evaluate(el=>getComputedStyle(el).animationName),'none');
   await page.goto(`${base}/?thread=${scout.threadId}&panel=bot`);
   await page.locator('.bot-hero').waitFor();
   assert.equal((await page.locator('.bot-hero').evaluate(el=>getComputedStyle(el).getPropertyValue('--mascot-color'))).trim(),scout.color,'teammate hero follows green mascot');
   await page.screenshot({path:path.join(output,'workspace-scout.png'),scale:'css'});
   await page.goto(`${base}/?thread=${threadId}&panel=teach`);
   await page.getByLabel('Note name',{exact:true}).fill('Writing preference');
   await page.getByLabel('What should they remember?',{exact:true}).fill('Keep the launch note concise. Synthetic UI check.');
   await page.getByRole('button',{name:'Save note',exact:true}).click();
   await page.getByText('Memory saved. Future tasks will use the correction.',{exact:true}).waitFor();
   const notes=await page.evaluate(async id=>(await fetch(`/api/extensions/memory/${id}`)).json(),pixel.id);
   assert.ok(notes.some((note:any)=>note.key==='Writing preference' && note.content.includes('Synthetic UI check')));
   await page.screenshot({path:path.join(output,'memory-saved.png'),scale:'css'});
   await page.goto(`${base}/?thread=${threadId}&panel=team`);
   const profile={kind:'openbot-teammate',version:1,bot:{name:'Imported fixture',role:'Preview only',instructions:'No external work',emoji:'o',mascot:'blob',color:'#d86889'},skills:[],routines:[]};
   await page.getByLabel('Import a teammate profile',{exact:true}).setInputFiles({name:'teammate.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(profile))});
   await page.getByRole('region',{name:'Profile preview'}).waitFor();
   const beforeImport=await page.evaluate(async()=> (await (await fetch('/api/state')).json()).bots.length);assert.equal(beforeImport,6,'choosing a profile does not import it');
   await page.screenshot({path:path.join(output,'profile-import-preview.png'),scale:'css'});
   await page.getByRole('button',{name:'Cancel import',exact:true}).click();
   console.log('PASS settings behavior: memory saved through real API; profile preview and cancellation do not create a teammate');
   await page.goto(`${base}/?thread=${threadId}&panel=team`); await page.locator('.workspace-team-grid').getByRole('button',{name:'Edit Pixel',exact:true}).click();
   await page.locator('.capability-bot').waitFor();
   assert.equal(new URL(page.url()).searchParams.get('thread'),threadId);
   await page.getByRole('button',{name:'Back to conversation',exact:true}).click(); await page.locator('#studio-message').waitFor();
   await page.getByRole('button',{name:'About Pixel',exact:true}).click();
   await page.screenshot({path:path.join(output,'teammate-profile.png'),scale:'css'});
   await page.getByRole('link',{name:'Edit & manage teammate',exact:false}).click();await page.locator('.capability-bot').waitFor();
   await page.getByRole('button',{name:'Back to conversation',exact:true}).click();await page.locator('#studio-message').waitFor();
   console.log('PASS all workspace screens: 14 desktop and phone routes, single focus ring, mobile return navigation, teammate edit, back to conversation');
 }
 const choiceFixture=new OpenBotDatabase(root,{dataDir:data});
 const originalChoice=choiceFixture.getBot(pixel.id)!;
 const optionalConnection=choiceFixture.upsertProvider({name:'Local choice fixture',authMode:'api_key',apiConfig:{baseUrl:'http://127.0.0.1:11434/v1',protocol:'openai-compatible',modelIds:['fixture-model']}});
 choiceFixture.close();
 await page.goto(`${base}/?thread=${threadId}&panel=provider`);
 await page.getByRole('combobox',{name:'Pixel connection',exact:true}).selectOption(optionalConnection.id);
 assert.equal(await page.getByRole('combobox',{name:'Pixel model',exact:true}).inputValue(),'','switching a connection still requires an explicit model');
 await page.getByRole('combobox',{name:'Pixel model',exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(output,'workspace-model-choice.png'),scale:'css'});
 const beforeChoice=await page.evaluate(async()=> (await (await fetch('/api/state')).json()).bots.find((bot:any)=>bot.name==='Pixel'));
 assert.equal(beforeChoice.providerInstanceId,originalChoice.providerInstanceId,'the current subscription stays active before model selection');
 await page.getByRole('combobox',{name:'Pixel model',exact:true}).selectOption(`openbot-${optionalConnection.id}/fixture-model`);
 await page.waitForFunction(async id => (await (await fetch('/api/state')).json()).bots.some((bot:any)=>bot.name==='Pixel' && bot.providerInstanceId===id),optionalConnection.id);
 const restoreChoice=new OpenBotDatabase(root,{dataDir:data});
 restoreChoice.updateBot(pixel.id,{providerInstanceId:originalChoice.providerInstanceId,model:originalChoice.model});restoreChoice.close();
 console.log('PASS model choice: connection selection alone changes nothing; explicit model selection saves the new pair');
 const expanded=new OpenBotDatabase(root,{dataDir:data});expanded.updateStudioSettings({maxTeammates:40});
 for(let i=1;i<=24;i++) expanded.createBot({name:`Synthetic teammate ${String(i).padStart(2,'0')} with a deliberately long name`,emoji:'',mascot:'blob',color:'#8780bf',role:'Layout stress fixture',instructions:'No external work',computerEnabled:false,browserEnabled:false});expanded.close();
 await page.reload();await page.getByLabel('Find a conversation').waitFor();await page.getByLabel('Find a conversation').fill('Synthetic teammate 24');await page.getByRole('button',{name:'Synthetic teammate 24 with a deliberately long name',exact:true}).waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByLabel('Find a conversation').fill('');await page.screenshot({path:path.join(output,'electron-30-conversations.png'),scale:'css'});
 console.log('PASS 30 conversations: searchable long names, scrolling layout, no horizontal page overflow');
 if (process.env.OPENBOT_TEST_ALL_SCREENS === '1') {
   const empty=new OpenBotDatabase(root,{dataDir:data});for(const bot of empty.listBots()) empty.retireBot(bot.id);empty.close();
   await page.goto(`${base}/?thread=team-room`);await page.locator('.refined-welcome').waitFor();
   await page.screenshot({path:path.join(output,'welcome.png'),scale:'css'});
   await page.getByRole('button',{name:'Create your first teammate',exact:false}).click();
   await page.getByRole('dialog',{name:'Create a teammate',exact:true}).waitFor();
   await page.waitForFunction(()=>document.querySelector('[role="combobox"][aria-label="AI connection"]')?.textContent?.includes('Choose your AI service'));
   assert.equal(await page.getByRole('combobox',{name:'Model',exact:true}).count(),0,'new teammate does not inherit a model before choosing a connection');
   await page.screenshot({path:path.join(output,'create-teammate.png'),scale:'css'});
   await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
   await page.goto(`${base}/?thread=team-room&panel=connectors`);
   await page.getByRole('button',{name:'Create a teammate',exact:true}).click();
   await page.getByRole('dialog',{name:'Create a teammate',exact:true}).waitFor();
   await page.keyboard.press('Escape');
   await phone.goto(`${base}/?thread=team-room`);await phone.locator('.refined-welcome').waitFor();
   await phone.screenshot({path:path.join(output,'phone-welcome.png')});
   console.log('PASS empty-team welcome and creation dialog: real retired roster, Escape restores conversation, no teammate automatically created');
 }

 assert.deepEqual(errors,[], 'desktop and phone routes have no uncaught renderer errors');

}finally{await browser?.close();if(electron){electron.process().kill("SIGTERM")}server.kill('SIGTERM');writeFileSync(path.join(root,'server.log'),log)}
